package course.NamingConvention;

public class javaNaming {
    /*
    How to name stuff in Java? #1

    #1:
    Variable and method names should start with lowercase latter.
    Ex: int count;
    public void add()
    {
    }

    #2:
    If there are more than one word that makes up a variable Name or method name
    Use "camel case"
    Ex: int personName;
    Ex: numberOfPeopleWhoArePresent;

    #3:
    Class names should start with an uppercase letter.
    Ex:
    class Person{}
    Don't use the $ symbol in names.
    it is intended for names that are automatically generated by tools.

    #4:
    Use all uppercase separated by underscore for multiple words while declaring CONSTANTS.
    Ex:
    public final static int PI=3.14;
    Ex:
    public final static int NO_OF_TARGETS = 4;

    #5;
    Choosing Meaningful Names:
    Ex:
    a = Math.pow(p * (1 + r / n), n * t)
    Ex:
    amount = Math.pow(principal * (1 + rateOfInterest / compoundCount), compoundCount * numberOfYears)

    */
}
